# version: '3'
# services:
#   db:
#     image: mysql:8.0
#     environment:
#       - MYSQL_ROOT_PASSWORD=root_password
#       - MYSQL_DATABASE=tickers_db
#       - MYSQL_USER=my_user   # Replace with your desired username
#       - MYSQL_PASSWORD=my_pass  # Replace with your desired password
#     volumes:
#       - ./db/setup.sql:/docker-entrypoint-initdb.d/setup.sql
#     ports:
#       - "3306:3306"  # Maps port 3306 in the container to port 3306 on the host
 
#   ticker-fetcher:
#     image: ticker/python
#     build:
#       context: ./ticker_fetcher
#     depends_on:
#       - db
#     environment:
#       - DB_USER=my_user   # Must match the MYSQL_USER from above
#       - DB_PASSWORD=my_pass   # Must match the MYSQL_PASSWORD from above
#       - DB_NAME=tickers_db
#       - DB_HOST=db
 
#   app:
#     build:
#       context: ./app
#     ports:
#       - 8501:8501
#     environment:
#       - OPENAI_API_KEY="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"
#     depends_on:
#       - ticker-fetcher

version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: tickers_db
      MYSQL_USER: my_user
      MYSQL_PASSWORD: my_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  ticker-fetcher:
    build: ./ticker_fetcher
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: my_user
      DB_PASSWORD: my_pass
      DB_NAME: tickers_db
    restart: on-failure

  app:
    # build: ./app
    build:
      context: .  # Root directory context
      dockerfile: app/Dockerfile
    ports:
      - "8501:8501"
    environment:
      OPENAI_API_KEY: "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"
    depends_on:
      ticker-fetcher:
        condition: service_completed_successfully

volumes:
  mysql_data: